### ISSUE TITLE
Current todo list

### ISSUE THREAD

**Issue by mathiasertl** [jabber-at/hp#1]
- [x] Add confirmation keys to admin.
- [ ] One key I received couldn't be opened - why?
  Tried this while being logged in with the wrong user - maybe that is the issue?
- [x] Password reset doesn't work: https://twitter.com/hatschew/status/772732106405478400
- [x] When the user wasn't yet created in the backend (didn't confirm email), set password yields a server-error. Set email works, but doesn't create the user either.
### Contact form
- [x] DnsBl, Blocklist
- [x] Rate limit
- [ ] Filter any URLs. Also HTML etc...
- [x] Minimum Length
